"""empty message

Revision ID: 60481b605829
Revises: 5df1dd13472e
Create Date: 2016-06-30 14:43:00.363000

"""

# revision identifiers, used by Alembic.
revision = '60481b605829'
down_revision = '5df1dd13472e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
