"""empty message

Revision ID: 659963ee0bdf
Revises: None
Create Date: 2016-06-29 14:50:16.673000

"""

# revision identifiers, used by Alembic.
revision = '659963ee0bdf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('head_portrait', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'head_portrait')
    ### end Alembic commands ###
