"""empty message

Revision ID: 95c11e5518d2
Revises: None
Create Date: 2016-07-19 16:31:52.606000

"""

# revision identifiers, used by Alembic.
revision = '95c11e5518d2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('seenable', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('seenable', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'seenable')
    op.drop_column('comments', 'seenable')
    ### end Alembic commands ###
